apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ingress-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.0.4/32

---

apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: qbittorrent-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.0.5/32

---

apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: plex-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.0.6/32

---

apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: filebrowser-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.0.7/32

---

apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: dnsmasq-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.0.8/32
