all:
  children:
    production:
      hosts:
        tothmarci25-homeserver:
          ansible_host: "{{ lookup('env', 'SERVER_IP') }}"
          ansible_port: "{{ lookup('env', 'SERVER_SSH_PORT') }}"
      vars:
        ansible_user: "{{ lookup('env', 'SERVER_USER') }}"
        ansible_become_pass: "{{ lookup('env', 'SUDO_PASSWORD') }}"
        ansible_ssh_private_key_file: "{{ lookup('env', 'ANSIBLE_SSH_KEY') }}"
        ansible_python_interpreter: /usr/bin/python3
        deploy_env: production
