all:
  children:
    staging:
      hosts:
        multipass-vm-name:
          ansible_host: "{{ lookup('env', 'SERVER_IP') }}"
      vars:
        ansible_user: "{{ lookup('env', 'SERVER_USER') }}"
        ansible_ssh_private_key_file: "{{ lookup('env', 'ANSIBLE_SSH_KEY') }}"
        ansible_python_interpreter: /usr/bin/python3
        environment: staging
