apiVersion: v1
kind: Service
metadata:
  name: plex-service
  labels:
    app: plex
  annotations:
    metallb.universe.tf/address-pool: plex-pool
spec:
  selector:
    app: plex
  ports:
    - name: web
      port: 32400
      targetPort: 32400
      protocol: TCP
  type: LoadBalancer
