apiVersion: v1
kind: Service
metadata:
  name: jackett-service
  labels:
    app: jackett
spec:
  selector:
    app: jackett
  ports:
    - name: web
      port: 80
      targetPort: 9117
      protocol: TCP
  type: ClusterIP
