storages:
- name: local
  nodeLabel: usb.local
  path: /mnt/local
  size: 20G
  storageClass: local-storage


apps:
  plex:
    extraVolumeMounts:
    - mountPath: /data
      name: local
      subPath: data/media
    - mountPath: /config
      name: local
      subPath: config/plex
    extraVolumes:
    - name: local
      persistentVolumeClaim:
        claimName: local-pvc
  radarr:
    extraVolumeMounts:
    - mountPath: /config
      name: local
      subPath: config/radarr
    - mountPath: /data
      name: local
      subPath: data
    extraVolumes:
    - name: local
      persistentVolumeClaim:
        claimName: local-pvc
