storages:
- name: ssd
  nodeLabel: usb.ssd
  path: /mnt/ssd
  size: 2000Gi
  storageClass: local-ssd
- name: red
  nodeLabel: usb.red
  path: /mnt/red
  size: 8000Gi
  storageClass: local-red
- name: wd
  nodeLabel: usb.wd
  path: /mnt/wd
  size: 2000Gi
  storageClass: local-wd


apps:
  filebrowser:
    extraVolumeMounts:
    - mountPath: /srv/ssd
      name: local-ssd
    - mountPath: /srv/wd
      name: local-wd
    - mountPath: /srv/red
      name: local-red
    - mountPath: /database/filebrowser.db
      name: local-ssd
      subPath: filebrowser/filebrowser.db
    - mountPath: /config/settings.json
      name: local-ssd
      subPath: filebrowser/settings.json
    extraVolumes:
    - name: local-ssd
      persistentVolumeClaim:
        claimName: ssd-pvc
    - name: local-wd
      persistentVolumeClaim:
        claimName: wd-pvc
    - name: local-red
      persistentVolumeClaim:
        claimName: red-pvc
  jackett:
    extraVolumeMounts:
    - mountPath: /config
      name: local-ssd
      subPath: config/jackett
    extraVolumes:
    - name: local-ssd
      persistentVolumeClaim:
        claimName: ssd-pvc
  plex:
    extraVolumeMounts:
    - mountPath: /config
      name: local-ssd
      subPath: config/plex
    - mountPath: /data
      name: local-ssd
      subPath: data/media
    - mountPath: /data/wd
      name: local-wd
      subPath: data/wd/media
    - mountPath: /data/red
      name: local-red
      subPath: data/red/media
    extraVolumes:
    - name: local-ssd
      persistentVolumeClaim:
        claimName: ssd-pvc
    - name: local-wd
      persistentVolumeClaim:
        claimName: wd-pvc
    - name: local-red
      persistentVolumeClaim:
        claimName: red-pvc
  qbittorrent:
    extraVolumeMounts:
    - mountPath: /config
      name: local-ssd
      subPath: config/qbittorrent
    - mountPath: /data/torrents
      name: local-ssd
      subPath: data/torrents
    - mountPath: /data/wd/torrents
      name: local-wd
      subPath: data/wd/torrents
    - mountPath: /data/red/torrents
      name: local-red
      subPath: data/red/torrents
    extraVolumes:
    - name: local-ssd
      persistentVolumeClaim:
        claimName: ssd-pvc
    - name: local-wd
      persistentVolumeClaim:
        claimName: wd-pvc
    - name: local-red
      persistentVolumeClaim:
        claimName: red-pvc
  radarr:
    extraVolumeMounts:
    - mountPath: /config
      name: local-ssd
      subPath: config/radarr
    - mountPath: /data
      name: local-ssd
      subPath: data
    - mountPath: /data/wd
      name: local-wd
      subPath: data/wd
    - mountPath: /data/red
      name: local-red
      subPath: data/red
    extraVolumes:
    - name: local-ssd
      persistentVolumeClaim:
        claimName: ssd-pvc
    - name: local-wd
      persistentVolumeClaim:
        claimName: wd-pvc
    - name: local-red
      persistentVolumeClaim:
        claimName: red-pvc
  sonarr:
    extraVolumeMounts:
    - mountPath: /config
      name: local-ssd
      subPath: config/sonarr
    - mountPath: /data
      name: local-ssd
      subPath: data
    - mountPath: /data/wd
      name: local-wd
      subPath: data/wd
    - mountPath: /data/red
      name: local-red
      subPath: data/red
    extraVolumes:
    - name: local-ssd
      persistentVolumeClaim:
        claimName: ssd-pvc
    - name: local-wd
      persistentVolumeClaim:
        claimName: wd-pvc
    - name: local-red
      persistentVolumeClaim:
        claimName: red-pvc
