storages:
- name: ssd
  nodeLabel: usb.ssd
  path: /mnt/ssd
  size: 2000Gi
  storageClass: local-ssd
- name: red
  nodeLabel: usb.red
  path: /mnt/red
  size: 8000Gi
  storageClass: local-red
- name: wd
  nodeLabel: usb.wd
  path: /mnt/wd
  size: 2000Gi
  storageClass: local-wd


apps:
  plex:
    extraVolumeMounts:
    - mountPath: /config
      name: local-ssd
      subPath: config/plex
    - mountPath: /data
      name: local-ssd
      subPath: data/media
    - mountPath: /data/wd
      name: local-wd
      subPath: data/wd/media
    - mountPath: /data/red
      name: local-red
      subPath: data/red/media
    extraVolumes:
    - name: local-ssd
      persistentVolumeClaim:
        claimName: ssd-pvc
    - name: local-wd
      persistentVolumeClaim:
        claimName: wd-pvc
    - name: local-red
      persistentVolumeClaim:
        claimName: red-pvc
