ipAddressPools:
  - name: ingress-pool
    addresses:
      - 192.168.0.4/32
  
  - name: qbittorrent-pool
    addresses:
      - 192.168.0.5/32
  
  - name: plex-pool
    addresses:
      - 192.168.0.6/32
  
  - name: dnsmasq-pool
    addresses:
      - 192.168.0.8/32

l2Advertisement:
  ipAddressPools:
    - ingress-pool
    - dnsmasq-pool
    - plex-pool
    - qbittorrent-pool
