# Production environment values for vault persistent volumes

# Node name where the PVs will be created
nodeName: "tothmarci25-homeserver"

# Vault data persistent volume configuration
data:
  storage: "10Gi"
  localPath: "/mnt/ssd/vault-data"
  storageClassName: "vault-storage-pv"

# Vault audit persistent volume configuration
audit:
  storage: "5Gi"
  localPath: "/mnt/ssd/vault-audit"
  storageClassName: "vault-audit-pv"
