apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: private-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
    # - host: test-app.private-app.local
    #   http:
    #     paths:
    #       - path: /
    #         pathType: Prefix
    #         backend:
    #           service:
    #             name: private-test-app-service
    #             port:
    #               number: 80
    - host: qbittorrent.home
      http:
        paths:
           - path: /
             pathType: Prefix
             backend:
               service:
                 name: qbittorrent-webui
                 port:
                   number: 80

    - host: sonarr.home
      http:
        paths:
           - path: /
             pathType: Prefix
             backend:
               service:
                 name: sonarr-webui
                 port:
                   number: 80

    - host: radarr.home
      http:
        paths:
           - path: /
             pathType: Prefix
             backend:
               service:
                 name: radarr-service
                 port:
                   number: 80

    - host: jackett.home
      http:
        paths:
           - path: /
             pathType: Prefix
             backend:
               service:
                 name: jackett-webui
                 port:
                   number: 80

    - host: plex.tothmarci25.com
      http:
        paths:
           - path: /
             pathType: Prefix
             backend:
               service:
                 name: plex-service
                 port:
                   number: 32400

    - host: argocd.tothmarci25.com
      http:
        paths:
           - path: /
             pathType: Prefix
             backend:
               service:
                 name: argocd-server
                 port:
                   number: 80

    - host: test.tothmarci25.com
      http:
        paths:
           - path: /
             pathType: Prefix
             backend:
               service:
                 name: plex-service
                 port:
                   number: 32400

#    - host: plex.home
#      http:
#        paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: plex-service
#                 port:
#                   number: 32400

    - host: filebrowser.home
      http:
        paths:
           - path: /
             pathType: Prefix
             backend:
               service:
                 name: filebrowser-svc
                 port:
                   number: 80
